version: "2"
linters:
  default: all
  disable:
    - cyclop            # covered by gocyclo
    - depguard          # unnecessary for small libraries
    - exhaustruct       # don't _always_ need to exhaustively create struct
    - funlen            # rely on code review to limit function length
    - gocognit          # dubious "cognitive overhead" quantification
    - inamedparam       # convention is not followed
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - mnd               # status codes are clearer than constants
    - nlreturn          # generous whitespace violates house style
    - noinlineerr
    - nonamedreturns    # named returns are fine; it's *bare* returns that are bad
    - protogetter       # too many false positives
    - testpackage       # internal tests are fine
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
    - wsl_v5            # generous whitespace violates house style
  settings:
    dupl:
      threshold: 200
    errcheck:
      check-type-assertions: true
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print
        - pattern: ^log\.
        - pattern: ^print$
        - pattern: ^println$
        - pattern: ^panic$
    godox:
      # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
      # temporary hacks, and use godox to prevent committing them.
      keywords:
        - FIXME
    importas:
      no-unaliased: true
    varnamelen:
      ignore-decls:
        - T any
        - i int
        - wg sync.WaitGroup
        - ok bool
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Don't ban use of fmt.Errorf to create new errors, but the remaining
      # checks from err113 are useful.
      - linters:
          - err113
        text: do not define dynamic errors
      # Allow fmt.Printf in examples
      - linters:
          - forbidigo
        path: franz/example/main.go
        text: fmt.Printf
      - linters:
          - forbidigo
        path: confluent/example/main.go
        text: fmt.Printf

formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
